using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TimeSquare.Model
{
    public class Note
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        // external Id, easier to reference: 1,2,3 or A, B, C etc.
        public string Id { get; set; }

        public string Body { get; set; } = string.Empty;

        [BsonDateTimeOptions]
        public DateTime UpdatedOn { get; set; } = DateTime.Now;

        public NoteImage HeaderImage { get; set; }

        public int UserId { get; set; } = 0;

        public string Testcase { get; set; }

        public string ExecutionTime { get; set; }

        public string MachineName { get; set; }

        public string OperatingSystem { get; set; }

        public string AvgCpuUsage { get; set; }

        public string DateOfExecution { get; set; }

        public string AvgRamUsage { get; set; }

        public string Result { get; set; }

        public string AvgNetworkUsage { get; set; }

        public string Category { get; set; }

        public string Author { get; set; }

        public string Description { get; set; }

        public string Harness { get; set; }

        public string Squad { get; set; }

        public string Date { get; set; }

        public string Duration { get; set; }

        public string Screenshot { get; set; }

        public string Video { get; set; }

        public string ScreenshotAzure { get; set; }

        public string VideoAzure { get; set; }

        public string LogFileLocation { get; set; }

        public string LogFileLocationAzure { get; set; }

    }
}
